# FROM alpine:3.18

# WORKDIR /opt



#/opt/folder1/folder2
# FROM alpine:3.18

# WORKDIR /opt
# RUN echo "Welcome to Docker Labs" > opt.txt
# WORKDIR folder1
# RUN echo "Welcome to Docker Labs" > folder1.txt
# WORKDIR folder2
# RUN echo "Welcome to Docker Labs" > folder2.txt

#/var/tmp
# FROM alpine:3.18
# WORKDIR /opt/folder1
# RUN echo "Welcome to Docker Labs" > opt.txt
# WORKDIR /var/tmp/

#/myfolder
FROM alpine:3.18
ENV DIRPATH /myfolder
WORKDIR $DIRPATH