# FROM alpine:3.18

# ENTRYPOINT ["/bin/echo", "Hi, your ENTRYPOINT instruction in Exec Form !"]

FROM alpine:3.18


ENTRYPOINT echo "Hi, your ENTRYPOINT instruction in Shell Form !"

#替换掉镜像本来的内容
#docker container run --entrypoint "/bin/echo" entrypoint:v2 "Hello, Welocme to Docker Meetup! "